export var climbers = [
  {
    Name: 'Dorje',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Lhakpa',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Norbu',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Pasang',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Pema',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Sange',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Temba',
    Date: '1922-06-07',
    Age: 'unknown',
    Expedition: '1922 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Man Bahadur',
    Date: '1924-05-13',
    Age: 'unknown',
    Expedition: '1924 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Pneumonia',
    GeneralLocation: 'Rongbuk B.C.',
    SpecificLocation: 'Above Rongbuk B.C.',
  },
  {
    Name: 'Lance-Naik Shamsherpun',
    Date: '1924-05-17',
    Age: 'unknown',
    Expedition: '1924 British Mount Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Brain hemorrhage',
    GeneralLocation: 'Rongbuk B.C.',
    SpecificLocation: 'Above Rongbuk B.C.',
  },
  {
    Name: 'Andrew Irvine',
    Date: '1924-06-09',
    Age: 22,
    Expedition: '1924 British Mount Everest Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Disappeared; body never found; cause of death unknown',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'George Mallory',
    Date: '1924-06-09',
    Age: 37,
    Expedition: '1924 British Mount Everest Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath:
      'Disappeared; body found in 1999; evidence suggests Mallory died from being accidentally struck by his ice axe following a fall.',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Maurice Wilson',
    Date: '1934-05-31',
    Age: 36,
    Expedition: 'Solo Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath:
      'Body found 1935; cause of death possibly exhaustion, exposure or starvation.',
    GeneralLocation: 'East Rongbuk glacier',
  },
  {
    Name: 'Dorje Mingma',
    Date: '1952-10-31',
    Age: 'unknown',
    Expedition: 'Swiss Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Falling ice',
    GeneralLocation: 'Lhotse Face',
  },
  {
    Name: 'Wang Ji',
    Date: '1960-04-11',
    Age: 'unknown',
    Expedition: 'Chinese Expedition Northern Slope',
    Nationality: 'China',
    CauseOfDeath: 'Mountain sickness',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Shao Shi-Ching',
    Date: '1960-04-29',
    Age: 'unknown',
    Expedition: 'Chinese Expedition Northern Slope',
    Nationality: 'China',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Nawang Tshering',
    Date: '1962-04-28',
    Age: 'unknown',
    Expedition: 'Chinese Expedition Northern Slope',
    Nationality: 'Nepal',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'Lhotse face',
  },
  {
    Name: 'Jake Breitenbach',
    Date: '1963-03-23',
    Age: 27,
    Expedition: "Norman Dyhrenfurth's American Mount Everest Expedition",
    Nationality: 'United States',
    CauseOfDeath: 'Crushed under serac',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Ma Gao-shu',
    Date: '1966-05-01',
    Age: 'unknown',
    Expedition: 'Chinese Everest Expedition',
    Nationality: 'China',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Phu Dorje',
    Date: '1969-10-18',
    Age: 'unknown',
    Expedition: 'Japanese Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall into a crevice',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Nima Dorje',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Kunga Norbu',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Mima Norbu',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Pasang',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Kami Tshering',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Kyak Tshering',
    Date: '1970-04-05',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Kyak Tshering',
    Date: '1970-04-09',
    Age: 36,
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 5525,
  },
  {
    Name: 'Kiyoshi Narita',
    Date: '1970-04-21',
    Age: 'unknown',
    Expedition: 'Japanese Skiing Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'unknown',
    Elevation: 6150,
  },
  {
    Name: 'Harsh Vardhan',
    Date: '1971-04-18',
    Age: 'unknown',
    Expedition: 'International Expedition of 1971',
    Nationality: 'India',
    CauseOfDeath:
      'Succumbed after falling and being suspended above a crevice during a blizzard',
    GeneralLocation: 'unknown',
    Elevation: 6900,
  },
  {
    Name: 'Tony Tighe',
    Date: '1972-11-16',
    Age: 'unknown',
    Expedition: 'Mt. Qomolangma expedition',
    Nationality: 'Australia',
    CauseOfDeath: 'Crushed under serac',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Jangbu',
    Date: '1973-10-12',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'S.W. Face',
  },
  {
    Name: 'Gérard Devouassoux',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'France',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Pemba Dorje',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Lhakpa',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Nawang Lutuk',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Nima Wangchu',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Sanu Wongal',
    Date: '1974-09-09',
    Age: 'unknown',
    Expedition: 'French West Ridge Direct expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6400,
  },
  {
    Name: 'Wu Zhuong Yue',
    Date: '1975-05-04',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'China',
    CauseOfDeath: 'Exhaustion, fall',
    GeneralLocation: 'unknown',
    Elevation: 8500,
  },
  {
    Name: 'Mick Burke',
    Date: '1975-09-26',
    Age: 34,
    Expedition: "Bonington's 1975 Everest expedition",
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Terry Thompson',
    Date: '1976-04-10',
    Age: 'unknown',
    Expedition: 'British-Nepal Army Everest Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Camp 2',
  },
  {
    Name: 'Dawa Nuru',
    Date: '1978-04-18',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Shi Ming-ji',
    Date: '1978-04-18',
    Age: 'unknown',
    Expedition: 'Chinese Iranian Expedition',
    Nationality: 'China',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Ang Phu',
    Date: '1979-05-16',
    Age: 'unknown',
    Expedition: 'Yugoslavian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Ray Genet',
    Date: '1979-10-02',
    Age: 48,
    Expedition: 'Gerhard Schmatz German Expedition',
    Nationality: 'United States',
    CauseOfDeath: 'Exposure, exhaustion',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8400,
  },
  {
    Name: 'Hannelore Schmatz',
    Date: '1979-10-02',
    Age: 39,
    Expedition: 'Gerhard Schmatz German Expedition',
    Nationality: 'Germany',
    CauseOfDeath: 'Exposure, exhaustion',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8400,
  },
  {
    Name: 'Wang Hong-bao',
    Date: '1979-10-12',
    Age: 'unknown',
    Expedition: 'Japanese Alpine Club reconnaissance expedition',
    Nationality: 'China',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Lou Lan',
    Date: '1979-10-12',
    Age: 'unknown',
    Expedition: 'Japanese Alpine Club reconnaissance expedition',
    Nationality: 'China',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Nima Thaxi',
    Date: '1979-10-12',
    Age: 'unknown',
    Expedition: 'Japanese Alpine Club reconnaissance expedition',
    Nationality: 'China',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Akira Ube',
    Date: '1980-05-02',
    Age: 31,
    Expedition: 'Japanese Alpine Society Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Face',
    SpecificLocation: 'Hornbein Couloir',
    Elevation: 7900,
  },
  {
    Name: 'Nawang Kersang',
    Date: '1980-09-06',
    Age: 'unknown',
    Expedition: 'Italian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Mario Piana',
    Date: '1980-09-22',
    Age: 'unknown',
    Expedition: 'Italian Expedition',
    Nationality: 'Italy',
    CauseOfDeath: 'Crushed under serac',
    GeneralLocation: 'Lhotse Face',
  },
  {
    Name: 'Noboru Takenaka',
    Date: '1981-01-12',
    Age: 28,
    Expedition: 'Japanese Winter Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'W. Cwm',
    Elevation: 6900,
  },
  {
    Name: 'Marty Hoey',
    Date: '1982-05-15',
    Age: 30,
    Expedition: 'Whittaker American Expedition',
    Nationality: 'United States',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8000,
  },
  {
    Name: 'Peter Boardman',
    Date: '1982-05-17',
    Age: 31,
    Expedition: 'British Mount Everest Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'cause of death unknown',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8200,
  },
  {
    Name: 'Joe Tasker',
    Date: '1982-05-17',
    Age: 33,
    Expedition: 'British Mount Everest Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8200,
  },
  {
    Name: 'Ang Chuldim',
    Date: '1982-08-31',
    Age: 20,
    Expedition: 'Bill March Canadian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Dawa Dorje',
    Date: '1982-08-31',
    Age: 42,
    Expedition: 'Bill March Canadian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Pasang Sona',
    Date: '1982-08-31',
    Age: 38,
    Expedition: 'Bill March Canadian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Blair Griffiths',
    Date: '1982-09-02',
    Age: 33,
    Expedition: 'Bill March Canadian Expedition',
    Nationality: 'Canada',
    CauseOfDeath: 'Crushed under serac',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Lhakpa Tshering',
    Date: '1982-09-27',
    Age: 'unknown',
    Expedition: 'Spanish Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Internal hemorrhage',
    GeneralLocation: 'unknown',
    Elevation: 6770,
  },
  {
    Name: 'Nima Dorje',
    Date: '1982-10-14',
    Age: 'unknown',
    Expedition: 'Spanish Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'West Ridge',
    Elevation: 8300,
  },
  {
    Name: 'Yasuo Kato',
    Date: '1982-12-28',
    Age: 33,
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Toshiaki Kobayashi',
    Date: '1982-12-28',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Hironobu Kamuro',
    Date: '1983-10-08',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Pasang Temba',
    Date: '1983-10-08',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Hiroshi Yoshino',
    Date: '1983-10-09',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Ang Rinji',
    Date: '1984-03-26',
    Age: 'unknown',
    Expedition: 'Indian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Tony Swierzy',
    Date: '1984-04-03',
    Age: 27,
    Expedition: 'Micheal Lane British North Face Expedition',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 6238,
  },
  {
    Name: 'Hristo Ivanov Prodanov',
    Date: '1984-04-21',
    Age: 40,
    Expedition: 'Bulgarian West Face Expedition',
    Nationality: 'Bulgaria',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'West Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Fred From',
    Date: '1984-10-09',
    Age: 28,
    Expedition: 'Australian-New Zealand Expedition',
    Nationality: 'Australia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8000,
  },
  {
    Name: 'Craig Nottle',
    Date: '1984-10-09',
    Age: 23,
    Expedition: 'Australian-New Zealand Expedition',
    Nationality: 'Australia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8000,
  },
  {
    Name: 'Jozef Psotka',
    Date: '1984-10-16',
    Age: 50,
    Expedition: 'Australian-New Zealand Expedition',
    Nationality: 'Czechoslovakia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Ang Dorje',
    Date: '1984-10-24',
    Age: 35,
    Expedition: 'Mission to recover body of Hannelore Schmatz',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8400,
  },
  {
    Name: 'Yogendra Bahadur Thapa',
    Date: '1984-10-24',
    Age: 36,
    Expedition: 'Mission to recover body of Hannelore Schmatz',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8400,
  },
  {
    Name: 'Juanjo Navarro',
    Date: '1985-05-12',
    Age: 'unknown',
    Expedition: 'Basque Expedition',
    Nationality: 'Spain',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 7300,
  },
  {
    Name: 'Shinichi Ishii',
    Date: '1985-09-17',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Kiran Inder Kumar',
    Date: '1985-10-07',
    Age: 40,
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 7986,
  },
  {
    Name: 'Jai Bahugana',
    Date: '1985-10-11',
    Age: 'unknown',
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'Ranjeet Singh Bakshi',
    Date: '1985-10-11',
    Age: 'unknown',
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'Vijay Pal Singh Negi',
    Date: '1985-10-11',
    Age: 28,
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'M.U. Bhaskar Rao',
    Date: '1985-10-11',
    Age: 'unknown',
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'Ví­ctor Hugo Trujillo',
    Date: '1986-08-16',
    Age: 22,
    Expedition: 'unknown',
    Nationality: 'Chile',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Simon Burkhardt',
    Date: '1986-09-28',
    Age: 52,
    Expedition: 'Eiselin Sports Expedition',
    Nationality: 'Switzerland',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 7315,
  },
  {
    Name: 'Gyalu',
    Date: '1986-10-04',
    Age: 'unknown',
    Expedition: 'Eiselin Sports Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Crushed under serac',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Dawa Norbu',
    Date: '1986-10-17',
    Age: 'unknown',
    Expedition: 'Eiselin Sports Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'Below North Col',
  },
  {
    Name: 'Tsuttin Dorje',
    Date: '1987-01-30',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 7700,
  },
  {
    Name: 'Roger Marshall',
    Date: '1987-05-21',
    Age: 45,
    Expedition: 'unknown',
    Nationality: 'Canada',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'Near Summit',
    SpecificLocation: 'Hornbein Couloir',
  },
  {
    Name: 'Masao Yokoyama',
    Date: '1987-09-02',
    Age: 44,
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Drowned',
    GeneralLocation: 'East Rongbuk glacier',
  },
  {
    Name: 'Mangal Singh',
    Date: '1987-10-20',
    Age: 'unknown',
    Expedition: 'British Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Base camp',
  },
  {
    Name: 'Hidetaka Mizukoshi',
    Date: '1988-04-21',
    Age: 'unknown',
    Expedition:
      '35th Anniversary climb with Chinese, Japanese and Nepalese nationals',
    Nationality: 'Japan',
    CauseOfDeath: 'Heart attack (at Base camp)',
    GeneralLocation: 'Base camp',
  },
  {
    Name: 'Michel Parmentier',
    Date: '1988-09-20',
    Age: 'unknown',
    Expedition: 'International',
    Nationality: 'France',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'unknown',
    Elevation: 7700,
  },
  {
    Name: 'Narayan Shrestha',
    Date: '1988-09-21',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
    Elevation: 7200,
  },
  {
    Name: 'Lhakpa Sonam',
    Date: '1988-10-13',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8200,
  },
  {
    Name: 'Pasang Temba',
    Date: '1988-10-13',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8200,
  },
  {
    Name: 'Dušan Becík',
    Date: '1988-10-17',
    Age: 34,
    Expedition: 'IAMES Bratislava Expedition',
    Nationality: 'Czechoslovakia',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8000,
  },
  {
    Name: 'Peter Božík',
    Date: '1988-10-17',
    Age: 34,
    Expedition: 'IAMES Bratislava Expedition',
    Nationality: 'Czechoslovakia',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8000,
  },
  {
    Name: 'Jaroslav Jaško',
    Date: '1988-10-17',
    Age: 26,
    Expedition: 'IAMES Bratislava Expedition',
    Nationality: 'Czechoslovakia',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8000,
  },
  {
    Name: 'Jozef Just',
    Date: '1988-10-17',
    Age: 33,
    Expedition: 'IAMES Bratislava Expedition',
    Nationality: 'Czechoslovakia',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8000,
  },
  {
    Name: 'Ang Lhakpa',
    Date: '1988-12-23',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Cerebral thrombosis',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'Dimitar Ilievski-Murato',
    Date: '1989-05-10',
    Age: 35,
    Expedition: 'unknown',
    Nationality: 'Yugoslavia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'South Col',
    SpecificLocation: 'Descending South Col Route',
  },
  {
    Name: 'Phu Dorje',
    Date: '1989-05-16',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'South Col',
    SpecificLocation: 'Descending South Col Route',
  },
  {
    Name: 'Mirosław Dąsal',
    Date: '1989-05-27',
    Age: 37,
    Expedition: 'Polish-led expedition that included four U.S. mountaineers',
    Nationality: 'Poland',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'West Ridge',
    Elevation: 7200,
  },
  {
    Name: 'Mirosław Gardzielewski',
    Date: '1989-05-27',
    Age: 35,
    Expedition: 'Polish-led expedition that included four U.S. mountaineers',
    Nationality: 'Poland',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'West Ridge',
    Elevation: 7200,
  },
  {
    Name: 'Andrzej Heinrich',
    Date: '1989-05-27',
    Age: 51,
    Expedition: 'Polish-led expedition that included four U.S. mountaineers',
    Nationality: 'Poland',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'West Ridge',
    Elevation: 7200,
  },
  {
    Name: 'Wacław Otręba',
    Date: '1989-05-27',
    Age: 50,
    Expedition: 'Polish-led expedition that included four U.S. mountaineers',
    Nationality: 'Poland',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'West Ridge',
    Elevation: 7200,
  },
  {
    Name: 'Eugeniusz Chrobak',
    Date: '1989-05-28',
    Age: 30,
    Expedition: 'Polish-led expedition that included four U.S. mountaineers',
    Nationality: 'Poland',
    CauseOfDeath: 'Avalanche injuries',
    GeneralLocation: 'Lhola camp',
  },
  {
    Name: 'Ang Pinjo',
    Date: '1989-12-12',
    Age: 'unknown',
    Expedition: 'South Korean expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Rafael Gómez-Menor',
    Date: '1990-09-14',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Spain',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Ang Sona',
    Date: '1990-09-14',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Badri Nath',
    Date: '1990-09-14',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Ham Sang-Hun',
    Date: '1990-10-07',
    Age: 'unknown',
    Expedition: 'Japanese Korean expedition',
    Nationality: 'South Korea',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Rüdiger Lang',
    Date: '1991-05-03',
    Age: 'unknown',
    Expedition: 'Austrian solo expedition',
    Nationality: 'Germany',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 7850,
  },
  {
    Name: 'Junichi Futagami',
    Date: '1991-05-27',
    Age: 'unknown',
    Expedition: 'Japanese solo expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    Elevation: 8700,
  },
  {
    Name: 'Deepak Kulkarni',
    Date: '1992-05-02',
    Age: 'unknown',
    Expedition: 'Indian expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Raymond Jacob',
    Date: '1992-05-02',
    Age: 'unknown',
    Expedition: 'Indian expedition',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Subba Singh',
    Date: '1992-05-11',
    Age: 43,
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Sher Singh',
    Date: '1992-05-23',
    Age: 'unknown',
    Expedition: 'Indian Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Manabu Hoshi',
    Date: '1992-05-23',
    Age: 'unknown',
    Expedition: 'Japanese Expedition',
    Nationality: 'Japan',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'unknown',
    Elevation: 8350,
  },
  {
    Name: 'Ang Tshering',
    Date: '1993-01-15',
    Age: 'unknown',
    Expedition: 'Spanish Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Pasang Lhamu Sherpa',
    Date: '1993-04-23',
    Age: 32,
    Expedition: 'Nepalese Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8750,
  },
  {
    Name: 'Sonam Tshering',
    Date: '1993-04-23',
    Age: 'unknown',
    Expedition: 'Nepalese Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8750,
  },
  {
    Name: 'Lobsang Tshering Bhutia',
    Date: '1993-05-10',
    Age: 41,
    Expedition: "40th anniversary of Tenzing Norgay's climb",
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8750,
  },
  {
    Name: 'Nam Won-Woo',
    Date: '1993-05-16',
    Age: 'unknown',
    Expedition: 'South Korean expedition',
    Nationality: 'South Korea',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8450,
  },
  {
    Name: 'A Jin-Seob',
    Date: '1993-05-17',
    Age: 'unknown',
    Expedition: 'South Korean expedition',
    Nationality: 'South Korea',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8450,
  },
  {
    Name: 'Karl Henize',
    Date: '1993-10-05',
    Age: 66,
    Expedition: 'American expedition',
    Nationality: 'United States',
    CauseOfDeath: 'High-altitude pulmonary edema',
    GeneralLocation: '6400m',
  },
  {
    Name: 'Antonio Miranda',
    Date: '1993-10-07',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Spain',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Prem Thapa',
    Date: '1994-04-06',
    Age: 'unknown',
    Expedition: 'German Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'High-altitude cerebral edema',
    GeneralLocation: 'unknown',
  },
  {
    Name: "Shih Fang-Fang 'Norman'",
    Date: '1994-05-09',
    Age: 27,
    Expedition: 'Taiwanese',
    Nationality: 'Taiwan',
    CauseOfDeath: 'Exhaustion and/or exposure',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Giuseppe Vigani-Fang',
    Date: '1994-05-18',
    Age: 'unknown',
    Expedition: 'Italian Expedition',
    Nationality: 'Italy',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Mike Rheinberger',
    Date: '1994-05-27',
    Age: 53,
    Expedition: 'Australian Expedition',
    Nationality: 'Australia',
    CauseOfDeath:
      '150m fall. He showed signs of Exhaustion, Dehydration, Cerebral Oedema, Retinal Hemorrages and possible blood clots in his upper legs.',
    GeneralLocation: 'unknown',
    Elevation: 8500,
  },
  {
    Name: 'Mingma Norbu',
    Date: '1994-09-12',
    Age: 'unknown',
    Expedition: 'Norwegian Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Kami Rita',
    Date: '1995-05-06',
    Age: 'unknown',
    Expedition: 'American Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Lhakpa Nuru',
    Date: '1995-09-10',
    Age: 'unknown',
    Expedition: 'South Korean Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'unknown',
    Elevation: 6900,
  },
  {
    Name: 'Zangbu',
    Date: '1995-10-14',
    Age: 'unknown',
    Expedition: 'South Korean Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Near Summit',
  },
  {
    Name: 'Chen Yu-Nan',
    Date: '1996-05-09',
    Age: 36,
    Expedition: "'Makalu' Gau Ming-Ho Taiwanese expedition",
    Nationality: 'Taiwan',
    CauseOfDeath: 'Injuries from a fall',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Unknown climber',
    Date: '1996-05',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Hungary',
    CauseOfDeath: 'Suspected high-altitude cerebral edema, coma',
    GeneralLocation: 'N.E. Ridge',
    SpecificLocation: 'Camp 6',
    Elevation: 8300,
  },
  {
    Name: 'Scott Fischer',
    Date: '1996-05-11',
    Age: 40,
    Expedition: 'Mountain Madness',
    Nationality: 'United States',
    CauseOfDeath:
      'Suspected high-altitude cerebral edema, exhaustion, frostbite and exposure.',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8300,
  },
  {
    Name: 'Rob Hall',
    Date: '1996-05-11',
    Age: 35,
    Expedition: 'Adventure Consultants',
    Nationality: 'New Zealand',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Summit',
  },
  {
    Name: 'Doug Hansen',
    Date: '1996-05-11',
    Age: 46,
    Expedition: 'Adventure Consultants',
    Nationality: 'United States',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Summit',
  },
  {
    Name: 'Andrew Harris',
    Date: '1996-05-11',
    Age: 31,
    Expedition: 'Adventure Consultants',
    Nationality: 'New Zealand',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Dorje Morup',
    Date: '1996-05-11',
    Age: 47,
    Expedition: 'Indo-Tibetan Border Police',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Yasuko Namba',
    Date: '1996-05-11',
    Age: 47,
    Expedition: 'Adventure Consultants',
    Nationality: 'Japan',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'South Col',
  },
  {
    Name: 'Tsewang Paljor',
    Date: '1996-05-11',
    Age: 28,
    Expedition: 'Indo-Tibetan Border Police',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Tsewang Samanla',
    Date: '1996-05-11',
    Age: 38,
    Expedition: 'Indo-Tibetan Border Police',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Reinhard Wlasich',
    Date: '1996-05-19',
    Age: 'unknown',
    Expedition: 'Austrian',
    Nationality: 'Austria',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'North Face',
    SpecificLocation: 'Great Couloir',
    Elevation: 8300,
  },
  {
    Name: 'Bruce Herrod',
    Date: '1996-05-25',
    Age: 37,
    Expedition: 'South African/British',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Rope accident',
    GeneralLocation: 'S.E. Ridge',
    SpecificLocation: 'Hillary Step',
  },
  {
    Name: 'Ngawang Topche',
    Date: '1996-06-06',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Lapsed into Coma on 23 Apr 1996; later died in hospital',
    GeneralLocation: 'Camp 2',
  },
  {
    Name: 'Yves Bouchon',
    Date: '1996-09-25',
    Age: 'unknown',
    Expedition: 'French/Belgian/Swiss',
    Nationality: 'France',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Lhotse Face',
    Elevation: 7400,
  },
  {
    Name: 'Lopsang Jangbu',
    Date: '1996-09-25',
    Age: 25,
    Expedition: 'Japanese',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Lhotse Face',
    Elevation: 7400,
  },
  {
    Name: 'Dawa',
    Date: '1996-09-25',
    Age: 'unknown',
    Expedition: 'South Korea',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Lhotse Face',
    Elevation: 7400,
  },
  {
    Name: 'Malcolm Duff',
    Date: '1997-04-23',
    Age: 'unknown',
    Expedition: 'British',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Nima Rinzi',
    Date: '1997-05-06',
    Age: 'unknown',
    Expedition: 'Malaysian',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Lhotse Face',
  },
  {
    Name: 'Aleksandr Torochin',
    Date: '1997-05-07',
    Age: 'unknown',
    Expedition: 'Russian',
    Nationality: 'Russia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8400,
  },
  {
    Name: 'Ivan Plotnikov',
    Date: '1997-05-07',
    Age: 'unknown',
    Expedition: 'Russian',
    Nationality: 'Russia',
    CauseOfDeath: 'Exhaustion and/or exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Nikolai Shevtchenko',
    Date: '1997-05-07',
    Age: 'unknown',
    Expedition: 'Russian',
    Nationality: 'Russia',
    CauseOfDeath: 'Exhaustion and/or exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Mingma',
    Date: '1997-05-07',
    Age: 'unknown',
    Expedition: 'Russian',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Peter Kowalzik',
    Date: '1997-05-08',
    Age: 'unknown',
    Expedition: 'Polish',
    Nationality: 'Germany',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Tenzing Nuru',
    Date: '1997-09-08',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Disappearance (likely accidental death during climb)',
    GeneralLocation: 'S.E. Ridge',
  },
  {
    Name: 'Choi Byong-Soo',
    Date: '1997-09-08',
    Age: 'unknown',
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'North Col',
    SpecificLocation: 'North Col Flank',
  },
  {
    Name: 'Sergei Arsentiev',
    Date: '1998-05-23',
    Age: 'unknown',
    Expedition: 'Russian/French',
    Nationality: 'United States',
    CauseOfDeath: '100m Fall.',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Francys Arsentiev',
    Date: '1998-05-24',
    Age: 40,
    Expedition: 'Russian/French',
    Nationality: 'United States',
    CauseOfDeath: 'Exposure and/or cerebral oedema',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Mark Jennings',
    Date: '1998-05-25',
    Age: 'unknown',
    Expedition: 'British',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Roger Buick',
    Date: '1998-05-26',
    Age: 'unknown',
    Expedition: 'New Zealand',
    Nationality: 'New Zealand',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Vasyl Kopytko',
    Date: '1999-05-08',
    Age: 'unknown',
    Expedition: 'Ukrainian',
    Nationality: 'Ukraine',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Michael Matthews',
    Date: '1999-05-13',
    Age: 23,
    Expedition: 'International',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'S.E. Ridge',
  },
  {
    Name: 'Tadeusz Kudelski',
    Date: '1999-05-18',
    Age: 44,
    Expedition: 'Polish International',
    Nationality: 'Poland',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Pascal Debrouwer',
    Date: '1999-05-18',
    Age: 29,
    Expedition: 'Belgian International',
    Nationality: 'Belgium',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Jeppe Stoltz',
    Date: '2000-05-20',
    Age: 27,
    Expedition: 'unknown',
    Nationality: 'Denmark',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Yan Gen-hua',
    Date: '2000-05-21',
    Age: 'unknown',
    Expedition: 'Chinese',
    Nationality: 'China',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Babu Chiri Sherpa',
    Date: '2001-04-29',
    Age: 35,
    Expedition: 'Nepalese',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Peter Ganner',
    Date: '2001-05-23',
    Age: 'unknown',
    Expedition: 'Austrian',
    Nationality: 'Austria',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Mark Auricht',
    Date: '2001-05-24',
    Age: 'unknown',
    Expedition: 'Australian',
    Nationality: 'Australia',
    CauseOfDeath: 'High-altitude cerebral edema',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Aleksei Nikiforov',
    Date: '2001-05-24',
    Age: 'unknown',
    Expedition: 'Russian',
    Nationality: 'Russia',
    CauseOfDeath:
      'Pre-existing illness exacerbated by freezing conditions, altitude',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Sándor Gárdos',
    Date: '2001-10-17',
    Age: 'unknown',
    Expedition: 'Hungarian',
    Nationality: 'Hungary',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 7800,
  },
  {
    Name: 'Peter Legate',
    Date: '2002-04-30',
    Age: 38,
    Expedition: 'British International',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Camp 3',
    SpecificLocation: 'Below Camp 3',
  },
  {
    Name: 'Zoran Miletic',
    Date: '2002-05-19',
    Age: 'unknown',
    Expedition: 'Russian International',
    Nationality: 'Yugoslavia',
    CauseOfDeath: 'Exact cause and date of death unknown',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 7800,
  },
  {
    Name: 'Marco Siffredi',
    Date: '2002-09-08',
    Age: 23,
    Expedition: 'International',
    Nationality: 'France',
    CauseOfDeath: 'Snowboarding accident',
    GeneralLocation: 'Hornbein Couloir',
  },
  {
    Name: 'Bhim Bahadur Gurung',
    Date: '2003-05-27',
    Age: 'unknown',
    Expedition: 'Indo-Nepal',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Icefall',
    Elevation: 5900,
  },
  {
    Name: 'Jan Krzysztof Liszewski',
    Date: '2003-05-25',
    Age: 55,
    Expedition: 'Independent',
    Nationality: 'Poland',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 7900,
  },
  {
    Name: 'Arnaud Saulnier',
    Date: '2003-05-08',
    Age: 'unknown',
    Expedition: 'French',
    Nationality: 'France',
    CauseOfDeath: 'Sickness in tent',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 5500,
  },
  {
    Name: 'Karma Gyalzen Sherpa',
    Date: '2003-05-24',
    Age: 'unknown',
    Expedition: 'International',
    Nationality: 'Nepal',
    CauseOfDeath: 'Altitude Sickness',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 6000,
  },
  {
    Name: 'Joon-Ho Baek',
    Date: '2004-05-18',
    Age: 38,
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Min Jang',
    Date: '2004-05-18',
    Age: 28,
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Mu-Taek Park',
    Date: '2004-05-18',
    Age: 36,
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8500,
  },
  {
    Name: 'Nils Antezana',
    Date: '2004-05-18',
    Age: 69,
    Expedition: 'International',
    Nationality: 'United States',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Hristo Ganchev Hristov',
    Date: '2004-05-20',
    Age: 27,
    Expedition: 'Bulgarian',
    Nationality: 'Bulgaria',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Shoko Ota',
    Date: '2004-05-20',
    Age: 63,
    Expedition: 'Japanese',
    Nationality: 'Japan',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Mariana Prodanova Maslarova',
    Date: '2004-05-23',
    Age: 43,
    Expedition: 'Bulgarian',
    Nationality: 'Bulgaria',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Sean Egan',
    Date: '2005-04-28',
    Age: 63,
    Expedition: 'Tim Redpath Expedition',
    Nationality: 'Canada',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 4600,
  },
  {
    Name: "Michael Corey O'Brien",
    Date: '2005-05-02',
    Age: 39,
    Expedition: 'Charity run with brother',
    Nationality: 'United States',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Icefall',
    SpecificLocation: 'Icefall South',
    Elevation: 5800,
  },
  {
    Name: 'Marko Lihteneker',
    Date: '2005-05-21',
    Age: 45,
    Expedition: 'unknown',
    Nationality: 'Slovenia',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Sirigereshiva Shankarappa Chaitanya',
    Date: '2005-05-30',
    Age: 'unknown',
    Expedition: 'India',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Dieter Kramer',
    Date: '2005-06-04',
    Age: 'unknown',
    Expedition: 'German',
    Nationality: 'Germany',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'unknown',
    Elevation: 8000,
  },
  {
    Name: 'Robert William Milne',
    Date: '2005-06-05',
    Age: 49,
    Expedition: 'unknown',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Organ failure due to freezing conditions',
    GeneralLocation: 'S.E. Ridge',
    Elevation: 8200,
  },
  {
    Name: 'Tuk Bahadur Thapa Magar Sherpa',
    Date: '2006-04-07',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Altitude',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 5500,
  },
  {
    Name: 'Ang Phinjo Sherpa',
    Date: '2006-04-21',
    Age: 50,
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
    Elevation: 5900,
  },
  {
    Name: 'Lhakpa Tseri',
    Date: '2006-04-21',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
    Elevation: 5900,
  },
  {
    Name: 'Dawa Temba',
    Date: '2006-04-21',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
    Elevation: 5900,
  },
  {
    Name: 'Jacques-Hugues Letrange',
    Date: '2006-05-06',
    Age: 'unknown',
    Expedition: 'American',
    Nationality: 'France',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Srikrishna',
    Date: '2006-05-14',
    Age: 'unknown',
    Expedition: 'Indian',
    Nationality: 'India',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'David Sharp',
    Date: '2006-05-15',
    Age: 34,
    Expedition: 'Asian Trekking',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Exposure and/or exhaustion',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8600,
  },
  {
    Name: 'Tomas Olsson',
    Date: '2006-05-16',
    Age: 30,
    Expedition: 'International',
    Nationality: 'Sweden',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Norton Couloir',
    Elevation: 8700,
  },
  {
    Name: 'Vitor Negrete',
    Date: '2006-05-19',
    Age: 38,
    Expedition: 'International',
    Nationality: 'Brazil',
    CauseOfDeath: 'Exposure and/or exhaustion',
    GeneralLocation: 'N.E. Ridge',
    SpecificLocation: 'Camp 3',
    Elevation: 8200,
  },
  {
    Name: 'Igor Plyushkin',
    Date: '2006-05-22',
    Age: 'unknown',
    Expedition: 'International',
    Nationality: 'Russia',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 7800,
  },
  {
    Name: 'Thomas Weber',
    Date: '2006-05-25',
    Age: 'unknown',
    Expedition: 'International',
    Nationality: 'Germany',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8700,
  },
  {
    Name: 'Yoshitomi Okura',
    Date: '2007-05-16',
    Age: 62,
    Expedition: 'Japanese',
    Nationality: 'Japan',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Maurizio Pierangelo',
    Date: '2007-05-17',
    Age: 46,
    Expedition: 'Italian',
    Nationality: 'Italy',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
  },
  {
    Name: 'Oh Hee-joon',
    Date: '2007-05-17',
    Age: 37,
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'S.W. Face',
  },
  {
    Name: 'Lee Hyun-jo',
    Date: '2007-05-17',
    Age: 34,
    Expedition: 'South Korean',
    Nationality: 'South Korea',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'S.W. Face',
  },
  {
    Name: 'Uwe Gianni Goltz',
    Date: '2008-05-21',
    Age: 44,
    Expedition: 'Sherpas documentary team',
    Nationality: 'Switzerland',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'South Col',
    Elevation: 8000,
  },
  {
    Name: 'Lhakpa Nuru',
    Date: '2009-05-07',
    Age: 'unknown',
    Expedition: 'Eco Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Veslav Chrzaszcz',
    Date: '2009-05-18',
    Age: 47,
    Expedition: 'Eco Everest Expedition',
    Nationality: 'Czech Republic',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Wenhong Wu',
    Date: '2009-05-19',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'China',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Frank Ziebarth',
    Date: '2009-05-21',
    Age: 29,
    Expedition: 'unknown',
    Nationality: 'Canada',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'North Summit',
    Elevation: 8700,
  },
  {
    Name: 'László Várkonyi',
    Date: '2010-04-26',
    Age: 54,
    Expedition: 'unknown',
    Nationality: 'Hungary',
    CauseOfDeath: 'Avalanche crevasse fall',
    GeneralLocation: 'North Col',
  },
  {
    Name: 'Tom Jørgensen',
    Date: '2010-05-19',
    Age: 56,
    Expedition: 'unknown',
    Nationality: 'Denmark',
    CauseOfDeath: 'High-altitude cerebral edema',
    GeneralLocation: 'unknown',
  },
  {
    Name: 'Peter Kinloch',
    Date: '2010-05-26',
    Age: 28,
    Expedition: 'International',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'unknown',
    Elevation: 8600,
  },
  {
    Name: 'Rick Hitch',
    Date: '2011-05-01',
    Age: 55,
    Expedition: 'International',
    Nationality: 'United States',
    CauseOfDeath: 'Heart attack',
    GeneralLocation: 'unknown',
    Elevation: 7010,
  },
  {
    Name: 'Shailendra Kumar Upadhyaya',
    Date: '2011-05-09',
    Age: 82,
    Expedition: 'Nepal',
    Nationality: 'Nepal',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Takashi Ozaki',
    Date: '2011-05-12',
    Age: 58,
    Expedition: 'International',
    Nationality: 'Japan',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'The Balcony',
    Elevation: 8400,
  },
  {
    Name: 'John Delaney',
    Date: '2011-05-21',
    Age: 42,
    Expedition: 'International',
    Nationality: 'Ireland',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'The Balcony',
    Elevation: 8400,
  },
  {
    Name: 'Hiroaki Kino',
    Date: '2011-09-15',
    Age: 48,
    Expedition: 'unknown',
    Nationality: 'Japan',
    CauseOfDeath: 'Cerebral apoplexy',
    GeneralLocation: 'Icefall',
    SpecificLocation: 'Lower Icefall',
  },
  {
    Name: 'Dawa Tenzing',
    Date: '2012-04-05',
    Age: 'unknown',
    Expedition: 'Himex',
    Nationality: 'Nepal',
    CauseOfDeath: 'Stroke',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Karsang Namgyal Sherpa',
    Date: '2012-04-19',
    Age: 'unknown',
    Expedition: 'Prestige Adventures',
    Nationality: 'Nepal',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Ramesh Gulve',
    Date: '2012-04-20',
    Age: 33,
    Expedition: 'Pune team',
    Nationality: 'India',
    CauseOfDeath: 'Stroke',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Namgyal Tshering Sherpa',
    Date: '2012-04-21',
    Age: 28,
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Camp 1',
  },
  {
    Name: 'Shriya Shah-Klorfine',
    Date: '2012-05-19',
    Age: 33,
    Expedition: 'Utmost Adventures',
    Nationality: 'Canada',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'Below Balcony',
    Elevation: 8300,
  },
  {
    Name: 'Eberhard Schaaf',
    Date: '2012-05-19',
    Age: 61,
    Expedition: 'Asian Trekking',
    Nationality: 'Germany',
    CauseOfDeath: 'High-altitude cerebral edema',
    GeneralLocation: 'Hillary Step',
  },
  {
    Name: 'Song Won-bin',
    Date: '2012-05-19',
    Age: 44,
    Expedition: 'Korean Everest & Lhotse Expedition',
    Nationality: 'South Korea',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'The Balcony',
  },
  {
    Name: 'Ha Wenyi',
    Date: '2012-05-20',
    Age: 55,
    Expedition: 'Mountain Experience',
    Nationality: 'China',
    CauseOfDeath: 'Suspected altitude sickness',
    GeneralLocation: 'The Balcony',
  },
  {
    Name: 'Juan José Polo Carbayo',
    Date: '2012-05-20',
    Age: 43,
    Expedition: 'Himalayan Guides',
    Nationality: 'Spain',
    CauseOfDeath: 'Exhaustion',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8300,
  },
  {
    Name: 'Ralf D. Arnold',
    Date: '2012-05-20',
    Age: 43,
    Expedition: 'Monterosa',
    Nationality: 'Germany',
    CauseOfDeath:
      'Exhaustion and related complications after breaking leg at Second Step',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8300,
  },
  {
    Name: 'Piseth Lim',
    Date: '2012-10-19',
    Age: 27,
    Expedition: 'International',
    Nationality: 'Cambodia',
    CauseOfDeath: 'Encountered inclement weather',
    GeneralLocation: 'unknown',
    Elevation: 4000,
  },
  {
    Name: 'Mingma Sherpa',
    Date: '2013-04-07',
    Age: 45,
    Expedition: 'Destination Himalaya',
    Nationality: 'Nepal',
    CauseOfDeath: 'Falling into a crevasse',
    GeneralLocation: 'unknown',
    SpecificLocation: 'Between Camps 1 and 2 in the Western Cwm',
  },
  {
    Name: 'DaRita Sherpa',
    Date: '2013-05-05',
    Age: 37,
    Expedition: 'International Mountain Guides',
    Nationality: 'Nepal',
    CauseOfDeath: 'Suspected cardiac arrest',
    GeneralLocation: 'Camp 3',
    SpecificLocation: 'Camp 3 on south side',
  },
  {
    Name: 'Sergey Ponomarev',
    Date: '2013-05-05',
    Age: 'unknown',
    Expedition: '7 Summits Club Everest expedition',
    Nationality: 'Russia',
    CauseOfDeath: 'Suspected cardiac arrest',
    GeneralLocation: 'unknown',
    SpecificLocation: 'At 100m above ABC on north side',
    Elevation: 6500,
  },
  {
    Name: 'Lobsang Sherpa',
    Date: '2013-05-07',
    Age: 22,
    Expedition: 'Chinese expedition team',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'unknown',
    SpecificLocation:
      'Between Camp 2 and Camp 3 on descent from Camp 4 (on south side)',
  },
  {
    Name: 'Alexey Bolotov',
    Date: '2013-05-15',
    Age: 50,
    Expedition: 'Russian South-West Face expedition',
    Nationality: 'Russia',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Icefall',
    Elevation: 5600,
  },
  {
    Name: 'Namgyal Sherpa',
    Date: '2013-05-17',
    Age: 35,
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'unknown',
    GeneralLocation: 'N.E. Ridge',
    Elevation: 8300,
  },
  {
    Name: 'Seo Sung-Ho',
    Date: '2013-05-21',
    Age: 33,
    Expedition: 'Zero to 8848 expedition',
    Nationality: 'South Korea',
    CauseOfDeath: 'Suspected Altitude Sickness',
    GeneralLocation: 'unknown',
    SpecificLocation: 'On descent (south side)',
  },
  {
    Name: 'Sajal Khaled (Mohammed Khaled Hossain)',
    Date: '2013-05-21',
    Age: 35,
    Expedition: 'unknown',
    Nationality: 'Bangladesh',
    CauseOfDeath: 'Suspected Altitude Sickness',
    GeneralLocation: 'South Col Camp',
  },
  {
    Name: 'Unknown climber',
    Date: '2013-05-22',
    Age: 'unknown',
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Suspected Altitude Sickness',
    GeneralLocation: 'Camp 4',
    SpecificLocation: 'Camp 4 (south side) in tent',
  },
  {
    Name: 'Mingma Tenzing Sherpa',
    Date: '2014-04-02',
    Age: 'unknown',
    Expedition: 'Peak Freaks Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'High-altitude pulmonary edema',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Mingma Nuru Sherpa',
    Date: '2014-04-18',
    Age: 46,
    Expedition: 'NBC Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Dorji Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'NBC Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Ang Tshiri Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'AAI Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Nima Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'AAI Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Phurba Ongyal Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Lapka Tenjing Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Chhiring Ongchu Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Dorjee Khatri',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventurist Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Then Dorjee Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventurist Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Phur Temba Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Adventurist Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Pasang Karma Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Jagged Globe Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Asman Tamang',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Himalayan Ecstasy Khotse Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Tenzing Chottar Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'AAI Everest Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche (missing)',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Ankaji Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Everest Chinese Dream Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'PemTenji Sherpa',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Everest Chinese Dream Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche (missing)',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Aash Bahadur Gurung',
    Date: '2014-04-18',
    Age: 'unknown',
    Expedition: 'Everest Chinese Dream Expedition 2014',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche (missing)',
    GeneralLocation: 'Icefall',
  },
  {
    Name: 'Daniel Paul Fredinburg',
    Date: '2015-04-25',
    Age: 33,
    Expedition: '2014 IMG Everest Expedition III',
    Nationality: 'United States',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Marisa Eve Girawong',
    Date: '2015-04-25',
    Age: 28,
    Expedition: 'H.G. Nuptse Expedition 2015',
    Nationality: 'United States',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Thomas Ely Taplin',
    Date: '2015-04-25',
    Age: 61,
    Expedition: 'TET Films & Photography',
    Nationality: 'United States',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Pemba Sherpa',
    Date: '2015-04-25',
    Age: 19,
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Dawa Tsering Sherpa',
    Date: '2015-04-25',
    Age: 33,
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Maila (Milan) Rai',
    Date: '2015-04-25',
    Age: 41,
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Chhimi Dawa Sherpa',
    Date: '2015-04-25',
    Age: 27,
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Pema Yishi (Hissi) Sherpa',
    Date: '2015-04-25',
    Age: 'unknown',
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Pasang Temba Sherpa',
    Date: '2015-04-25',
    Age: 'unknown',
    Expedition:
      'Tim Mosedale Everest Expedition (or H.G. Everest Expedition 2015)',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Krishna Kumar Rai',
    Date: '2015-04-25',
    Age: 'unknown',
    Expedition:
      'Tim Mosedale Everest Expedition (or H.G. Everest Expedition 2015)',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Zhenfang Ge',
    Date: '2015-04-25',
    Age: 43,
    Expedition: 'Dreamers Destination Track Lhotse Expedition 2015',
    Nationality: 'China',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Renu Fotedar',
    Date: '2015-04-25',
    Age: 49,
    Expedition: 'First Chinese Women Everest Expedition',
    Nationality: 'Australia, India',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Tenzing (Tengien) Bhote',
    Date: '2015-04-25',
    Age: 'unknown',
    Expedition:
      'Tim Mosedale Everest Expedition (or H.G. Everest Expedition 2015)',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Vinh B Truong',
    Date: '2015-04-25',
    Age: 48,
    Expedition: 'Trekker',
    Nationality: 'United States, Vietnam',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Lhakpa Chhiring Sherpa',
    Date: '2015-04-25',
    Age: 33,
    Expedition: 'First Chinese Women Everest Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Shiva Kumar Shrestha',
    Date: '2015-04-25',
    Age: 25,
    Expedition: 'Step Up Campaign Everest',
    Nationality: 'Nepal',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Scott Stark',
    Date: '2015-04-25',
    Age: 27,
    Expedition: 'MC Films & Photography',
    Nationality: 'United States',
    CauseOfDeath: 'Avalanche',
    'cause of death details':
      'Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Yomagato Horoshi',
    Date: '2015-04-27',
    Age: 56,
    Expedition: 'Dreamers Destination Lhotse Expedition',
    Nationality: 'Japan',
    CauseOfDeath:
      'Died in Kathmandu due to injuries sustained in the Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Jangbu Sherpa',
    Date: '2015-05-01',
    Age: 'unknown',
    Expedition: 'Adventure Consultants',
    Nationality: 'Nepal',
    CauseOfDeath:
      'Died in Kathmandu due to injuries sustained in the Base Camp avalanche following the April 2015 Nepal earthquake',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Charles MacAdams',
    Date: '2016-05-11',
    Age: 62,
    Expedition: 'unknown',
    Nationality: 'Canada',
    CauseOfDeath: 'Cardiac event',
    GeneralLocation: 'Base Camp',
    SpecificLocation: 'Base Camp North Side',
  },
  {
    Name: 'Phurba Sherpa',
    Date: '2016-05-19',
    Age: 25,
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall',
    GeneralLocation: 'Near Lhotse summit',
  },
  {
    Name: 'Eric Arnold',
    Date: '2016-05-21',
    Age: 35,
    Expedition: 'Arnold Coster Expeditions',
    Nationality: 'Netherlands',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'South Col',
    SpecificLocation: 'Camp 4',
  },
  {
    Name: 'Maria Elizabeth Strydom',
    Date: '2016-05-22',
    Age: 34,
    Expedition: 'Arnold Coster Expeditions',
    Nationality: 'Australia',
    CauseOfDeath: 'Snow blindness, stroke',
    GeneralLocation: 'Camp 4',
  },
  {
    Name: 'Subhash Pal',
    Date: '2016-05-22',
    Age: 44,
    Expedition: 'Trekking Camp Nepal',
    Nationality: 'India',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Camp 3',
  },
  {
    Name: 'Paresh Chandra Nath',
    Date: '2016-05-22',
    Age: 58,
    Expedition: 'Trekking Camp Nepal',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'The Balcony',
  },
  {
    Name: 'Goutam Ghosh',
    Date: '2016-05-22',
    Age: 'unknown',
    Expedition: 'Trekking Camp Nepal',
    Nationality: 'India',
    CauseOfDeath: 'Exposure',
    GeneralLocation: 'The Balcony',
  },
  {
    Name: 'Min Bahadur Sherchan',
    Date: '2017-05-05',
    Age: 85,
    Expedition: 'unknown',
    Nationality: 'Nepal',
    CauseOfDeath: 'Heart Attack',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Roland Yearwood',
    Date: '2017-05-20',
    Age: 50,
    Expedition: 'Everest Parivar Treks',
    Nationality: 'United States',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Balcony',
  },
  {
    Name: 'Vladimír Štrba',
    Date: '2017-05-21',
    Age: 48,
    Expedition: 'Everest Hard Way Slovak Expedition 2017',
    Nationality: 'Slovakia',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Camp IV, in the tent',
  },
  {
    Name: 'Francesco Enrico Marchetti',
    Date: '2017-05-21',
    Age: 54,
    Expedition: 'Expedition Himalaya',
    Nationality: 'Australia',
    CauseOfDeath: 'Altitude sickness',
    GeneralLocation: 'Camp IV',
  },
  {
    Name: 'Ravi Kumar',
    Date: '2017-05-21',
    Age: 27,
    Expedition: 'Arun treks and Expedition',
    Nationality: 'India',
    CauseOfDeath: 'Fall into a 200m crevasse',
    GeneralLocation: 'Balcony',
  },
  {
    Name: 'Ueli Steck',
    Date: '2017-04-30',
    Age: 40,
    Expedition: 'Solo',
    Nationality: 'Switzerland',
    CauseOfDeath: 'Fall 1000m, his body was found in the Western Cwm',
    GeneralLocation: '300m below the summit at the West Ridge',
  },
  {
    Name: 'Lam Babu Sherpa',
    Date: '2018-05-14',
    Age: 45,
    Expedition: 'Seven Summit Treks',
    Nationality: 'Nepal',
    CauseOfDeath: 'Disappearance (reportedly suffered from snow blindness)',
    GeneralLocation: 'Above South Col',
  },
  {
    Name: 'Pasang Norbu Sherpa',
    Date: '2018-05-18',
    Age: 41,
    Expedition: '7 Summits Club Expedition',
    Nationality: 'Nepal',
    CauseOfDeath: 'Stroke',
    GeneralLocation: '8550m N.E. Ridge',
  },
  {
    Name: 'Gjeorgi Petkov',
    Date: '2018-05-20',
    Age: 63,
    Expedition: 'Tim Mosedale Everest Expedition Spring 2018',
    Nationality: 'Macedonia',
    CauseOfDeath: 'Cardiac arrest',
    GeneralLocation: 'Above Camp III',
  },
  {
    Name: 'Nobukazu Kuriki',
    Date: '2018-05-21',
    Age: 36,
    Expedition: 'Solo',
    Nationality: 'Japan',
    CauseOfDeath:
      "Hypothermia, had previously reported 'persistent cough and pain' during attempt",
    GeneralLocation: 'Camp II',
  },
  {
    Name: 'Damai Sarki Sherpa',
    Date: '2018-05-21',
    Age: 37,
    Expedition: 'Himalayan Ascent, Seven Summit Treks',
    Nationality: 'Nepal',
    CauseOfDeath: 'Fall into a crevasse',
    GeneralLocation: 'Camp II',
  },
  {
    Name: 'Chris Daly',
    Date: '2019-04-20',
    Age: 35,
    Expedition: 'Solo',
    Nationality: 'United States',
    CauseOfDeath: 'Died after a fall while trekking down from base camp',
    GeneralLocation: 'Base Camp',
  },
  {
    Name: 'Séamus (Shay) Lawless',
    Date: '2019-05-16',
    Age: 39,
    Expedition: 'Seven Summit Treks',
    Nationality: 'Ireland',
    CauseOfDeath: 'Presumed dead after fall',
    GeneralLocation: 'Balcony',
  },
  {
    Name: 'Ravi Thakar',
    Date: '2019-05-17',
    Age: 28,
    Expedition: 'Seven Summit Treks',
    Nationality: 'India',
    CauseOfDeath: 'Altitude Sickness',
    GeneralLocation: 'Camp IV',
  },
  {
    Name: 'Donald Cash',
    Date: '2019-05-22',
    Age: 55,
    Expedition: 'Pioneer Adventures',
    Nationality: 'United States',
    CauseOfDeath: 'Altitude Sickness',
    GeneralLocation: 'Hillary Step',
  },
  {
    Name: 'Nihal Bagwan',
    Date: '2019-05-23',
    Age: 27,
    Expedition: 'Peak Promotions',
    Nationality: 'India',
    CauseOfDeath: 'Exhaustion on descent',
    GeneralLocation: 'near South Col',
  },
  {
    Name: 'Ernst Landgraf',
    Date: '2019-05-23',
    Age: 65,
    Expedition: 'Kobler & Partners',
    Nationality: 'Austria',
    CauseOfDeath: 'Exhaustion on descent',
    GeneralLocation: 'Tibet side at 8600m after summiting',
  },
  {
    Name: 'Anjali S Kulkarni',
    Date: '2019-05-23',
    Age: 54,
    Expedition: 'Transcent or Arun Treks',
    Nationality: 'India',
    CauseOfDeath: 'Exhaustion on descent',
    GeneralLocation: 'Near Camp IV',
  },
  {
    Name: 'Kalpana Dash',
    Date: '2019-05-23',
    Age: 52,
    Expedition: 'Dreamers Destination Treks',
    Nationality: 'India',
    CauseOfDeath: 'Exhaustion on descent',
    GeneralLocation: 'Near Balcony',
  },
  {
    Name: 'Kevin Hynes',
    Date: '2019-05-24',
    Age: 56,
    Expedition: '360 Expeditions',
    Nationality: 'Ireland',
    CauseOfDeath: 'Altitude Sickness',
    GeneralLocation: 'North Col',
  },
  {
    Name: 'Dhruba Bista',
    Date: '2019-05-24',
    Age: 'unknown',
    Expedition: 'Himalayan Ecstasy (Ski) Treks',
    Nationality: 'Nepal',
    CauseOfDeath: 'Exhaustion and altitude sickness',
    GeneralLocation: 'Base Camp following evacuation from Camp III',
  },
  {
    Name: 'Robin Haynes Fisher',
    Date: '2019-05-25',
    Age: 44,
    Expedition: 'Summit Climb/ Everest Parivar Expedition Ltd',
    Nationality: 'United Kingdom',
    CauseOfDeath: 'Exhaustion during descent',
    GeneralLocation: '100 metres below peak',
  },
  {
    Name: 'Christopher Jon Kullish',
    Date: '2019-05-27',
    Age: 62,
    Expedition: 'Climbing the Seven Summits',
    Nationality: 'United States',
    CauseOfDeath: 'Cardiac event during descent',
    GeneralLocation: 'South Col',
  },
]
